import type { NextPage } from 'next';
import Head from 'next/head';
import Banner from '../components/Banner';
import ClientCounter from '../components/ClientCounter';
import Features from '../components/Features';
import Footer from '../components/Footer';
import Header from '../components/Header';
import OurServices from '../components/OurServices';

const Home: NextPage = () => (
    <div>
        <Head>
            <title>Sell Bee</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <Banner />

        <Features />

        {/* <OurApproach /> */}

        <OurServices />

        {/* <OurResellers /> */}

        {/* <Testimonials /> */}

        {/* <StartReselling /> */}

        {/* <TrustedCompanies /> */}

        <ClientCounter />

        <Footer />
    </div>
);

export default Home;
