import type { NextPage } from 'next';
import Head from 'next/head';
import Banner from '../components/Banner';
import Features from '../components/Features';
import Footer from '../components/Footer';
import Header from '../components/Header';
import OurApproach from '../components/OurApproach';
import OurResellers from '../components/OurResellers';
import StartReselling from '../components/StartReselling';
import Testimonials from '../components/Testimonials';
import TrustedCompanies from '../components/TrustedCompanies';
import WhoWeAre from '../components/WhoWeAre';

const Home: NextPage = () => (
    <div>
        <Head>
            <title>Sell Bee</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />

        <Banner />

        <Features />

        <OurApproach />

        <WhoWeAre />

        <OurResellers />

        <Testimonials />

        <StartReselling />

        <TrustedCompanies />

        <Footer />
    </div>
);

export default Home;
